title: Jaehaerys Wang's Homepage
page-top-title: Jaehaerys Wang
top-section-bg-text: Computer Science
home-subtitle: Jaehaerys Wang&ensp;|&ensp;王昊龙
copyright-text: '&copy; Sen Li 2023-2025. All Rights Reserved.'
